[package]
name = "toy-rsa"
version = "0.1.0"
edition = "2021"
authors = ["Lance Miller"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.toy_rsa_lib]
git = "http://github.com/pdx-cs-rust/toy-rsa-lib"
